// Code generated by protoc-gen-go. DO NOT EDIT.
// source: etcdlet.proto

package etcdlet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddDetails struct {
	Name                     string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	InitialAdvertisePeerUrls string   `protobuf:"bytes,2,opt,name=initialAdvertisePeerUrls" json:"initialAdvertisePeerUrls,omitempty"`
	ListenPeerUrls           string   `protobuf:"bytes,3,opt,name=listenPeerUrls" json:"listenPeerUrls,omitempty"`
	ListenClientUrls         string   `protobuf:"bytes,4,opt,name=listenClientUrls" json:"listenClientUrls,omitempty"`
	AdvertiseClientUrls      string   `protobuf:"bytes,5,opt,name=advertiseClientUrls" json:"advertiseClientUrls,omitempty"`
	InitialClusterToken      string   `protobuf:"bytes,6,opt,name=initialClusterToken" json:"initialClusterToken,omitempty"`
	InitialCluster           string   `protobuf:"bytes,7,opt,name=initialCluster" json:"initialCluster,omitempty"`
	InitialClusterState      string   `protobuf:"bytes,8,opt,name=initialClusterState" json:"initialClusterState,omitempty"`
	Address                  string   `protobuf:"bytes,9,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *AddDetails) Reset()         { *m = AddDetails{} }
func (m *AddDetails) String() string { return proto.CompactTextString(m) }
func (*AddDetails) ProtoMessage()    {}
func (*AddDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_etcdlet_205acc584ca6bbfb, []int{0}
}
func (m *AddDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDetails.Unmarshal(m, b)
}
func (m *AddDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDetails.Marshal(b, m, deterministic)
}
func (dst *AddDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDetails.Merge(dst, src)
}
func (m *AddDetails) XXX_Size() int {
	return xxx_messageInfo_AddDetails.Size(m)
}
func (m *AddDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDetails.DiscardUnknown(m)
}

var xxx_messageInfo_AddDetails proto.InternalMessageInfo

func (m *AddDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddDetails) GetInitialAdvertisePeerUrls() string {
	if m != nil {
		return m.InitialAdvertisePeerUrls
	}
	return ""
}

func (m *AddDetails) GetListenPeerUrls() string {
	if m != nil {
		return m.ListenPeerUrls
	}
	return ""
}

func (m *AddDetails) GetListenClientUrls() string {
	if m != nil {
		return m.ListenClientUrls
	}
	return ""
}

func (m *AddDetails) GetAdvertiseClientUrls() string {
	if m != nil {
		return m.AdvertiseClientUrls
	}
	return ""
}

func (m *AddDetails) GetInitialClusterToken() string {
	if m != nil {
		return m.InitialClusterToken
	}
	return ""
}

func (m *AddDetails) GetInitialCluster() string {
	if m != nil {
		return m.InitialCluster
	}
	return ""
}

func (m *AddDetails) GetInitialClusterState() string {
	if m != nil {
		return m.InitialClusterState
	}
	return ""
}

func (m *AddDetails) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RemoveDetails struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDetails) Reset()         { *m = RemoveDetails{} }
func (m *RemoveDetails) String() string { return proto.CompactTextString(m) }
func (*RemoveDetails) ProtoMessage()    {}
func (*RemoveDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_etcdlet_205acc584ca6bbfb, []int{1}
}
func (m *RemoveDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDetails.Unmarshal(m, b)
}
func (m *RemoveDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDetails.Marshal(b, m, deterministic)
}
func (dst *RemoveDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDetails.Merge(dst, src)
}
func (m *RemoveDetails) XXX_Size() int {
	return xxx_messageInfo_RemoveDetails.Size(m)
}
func (m *RemoveDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDetails.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDetails proto.InternalMessageInfo

func (m *RemoveDetails) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type Response struct {
	Status               string   `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_etcdlet_205acc584ca6bbfb, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AddDetails)(nil), "etcdlet.AddDetails")
	proto.RegisterType((*RemoveDetails)(nil), "etcdlet.RemoveDetails")
	proto.RegisterType((*Response)(nil), "etcdlet.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Etcdlet service

type EtcdletClient interface {
	AddMember(ctx context.Context, in *AddDetails, opts ...grpc.CallOption) (*Response, error)
	RemoveMember(ctx context.Context, in *RemoveDetails, opts ...grpc.CallOption) (*Response, error)
}

type etcdletClient struct {
	cc *grpc.ClientConn
}

func NewEtcdletClient(cc *grpc.ClientConn) EtcdletClient {
	return &etcdletClient{cc}
}

func (c *etcdletClient) AddMember(ctx context.Context, in *AddDetails, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/etcdlet.etcdlet/addMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdletClient) RemoveMember(ctx context.Context, in *RemoveDetails, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/etcdlet.etcdlet/removeMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Etcdlet service

type EtcdletServer interface {
	AddMember(context.Context, *AddDetails) (*Response, error)
	RemoveMember(context.Context, *RemoveDetails) (*Response, error)
}

func RegisterEtcdletServer(s *grpc.Server, srv EtcdletServer) {
	s.RegisterService(&_Etcdlet_serviceDesc, srv)
}

func _Etcdlet_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdletServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdlet.etcdlet/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdletServer).AddMember(ctx, req.(*AddDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdlet_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdletServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdlet.etcdlet/RemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdletServer).RemoveMember(ctx, req.(*RemoveDetails))
	}
	return interceptor(ctx, in, info, handler)
}

var _Etcdlet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "etcdlet.etcdlet",
	HandlerType: (*EtcdletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addMember",
			Handler:    _Etcdlet_AddMember_Handler,
		},
		{
			MethodName: "removeMember",
			Handler:    _Etcdlet_RemoveMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "etcdlet.proto",
}

func init() { proto.RegisterFile("etcdlet.proto", fileDescriptor_etcdlet_205acc584ca6bbfb) }

var fileDescriptor_etcdlet_205acc584ca6bbfb = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4b, 0x4b, 0x03, 0x31,
	0x10, 0xb6, 0x0f, 0xfb, 0x18, 0x6c, 0xd1, 0x29, 0x94, 0xe0, 0x45, 0xd9, 0x83, 0x88, 0x87, 0x22,
	0x8a, 0x17, 0x3d, 0x95, 0xf6, 0xd2, 0x83, 0x20, 0xab, 0xfe, 0x80, 0xd4, 0xcc, 0x21, 0x98, 0xcd,
	0x96, 0x64, 0xda, 0x9b, 0x77, 0x7f, 0xb6, 0x34, 0xbb, 0xa9, 0x5b, 0xbb, 0xde, 0x32, 0xdf, 0x63,
	0xf2, 0xc1, 0x37, 0x30, 0x20, 0xfe, 0x50, 0x86, 0x78, 0xb2, 0x72, 0x39, 0xe7, 0xd8, 0x2d, 0xc7,
	0xe4, 0xbb, 0x05, 0x30, 0x55, 0x6a, 0x4e, 0x2c, 0xb5, 0xf1, 0x88, 0xd0, 0xb6, 0x32, 0x23, 0xd1,
	0xb8, 0x6c, 0x5c, 0xf7, 0xd3, 0xf0, 0xc6, 0x47, 0x10, 0xda, 0x6a, 0xd6, 0xd2, 0x4c, 0xd5, 0x86,
	0x1c, 0x6b, 0x4f, 0x2f, 0x44, 0xee, 0xdd, 0x19, 0x2f, 0x9a, 0x41, 0xf7, 0x2f, 0x8f, 0x57, 0x30,
	0x34, 0xda, 0x33, 0xd9, 0x9d, 0xa3, 0x15, 0x1c, 0x7f, 0x50, 0xbc, 0x81, 0xd3, 0x02, 0x99, 0x19,
	0x4d, 0x96, 0x83, 0xb2, 0x1d, 0x94, 0x07, 0x38, 0xde, 0xc2, 0x48, 0xc6, 0x8f, 0x2a, 0xf2, 0xe3,
	0x20, 0xaf, 0xa3, 0xb6, 0x8e, 0x32, 0xe1, 0xcc, 0xac, 0x3d, 0x93, 0x7b, 0xcb, 0x3f, 0xc9, 0x8a,
	0x4e, 0xe1, 0xa8, 0xa1, 0xb6, 0xb9, 0xf7, 0x61, 0xd1, 0x2d, 0x72, 0xef, 0xa3, 0x87, 0x9b, 0x5f,
	0x59, 0x32, 0x89, 0x5e, 0xdd, 0xe6, 0x40, 0xa1, 0x80, 0xae, 0x54, 0xca, 0x91, 0xf7, 0xa2, 0x1f,
	0x54, 0x71, 0x4c, 0x2e, 0x60, 0x90, 0x52, 0x96, 0x6f, 0x28, 0x96, 0x31, 0x84, 0xe6, 0x62, 0x1e,
	0xaa, 0x68, 0xa7, 0xcd, 0xc5, 0x3c, 0x49, 0xa0, 0x97, 0x92, 0x5f, 0xe5, 0xd6, 0x13, 0x8e, 0xa1,
	0xe3, 0x59, 0xf2, 0xda, 0x97, 0x55, 0x95, 0xd3, 0xdd, 0x17, 0xc4, 0x6a, 0xf1, 0x01, 0xfa, 0x52,
	0xa9, 0x67, 0xca, 0x96, 0xe4, 0x70, 0x34, 0x89, 0x07, 0xf0, 0xdb, 0xf6, 0xf9, 0xd9, 0x0e, 0x8c,
	0x7b, 0x93, 0x23, 0x7c, 0x82, 0x13, 0x17, 0x62, 0x94, 0xce, 0x71, 0x45, 0x54, 0x49, 0x57, 0x6b,
	0x5e, 0x76, 0xc2, 0x79, 0xdd, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x75, 0xf9, 0x06, 0xcf, 0x6f,
	0x02, 0x00, 0x00,
}
